{% set version = "2022.2.1" %}

package:
  name: pymor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymor/pymor-{{ version }}.tar.gz
  sha256: 538c84d2baf67a6473fb21f1afe7a387cc0c17e9ccb25b8fe83d6ef233b7d697

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - pymor-demo = pymor.scripts.pymor_demo:run
    - pymor-vis = pymor.scripts.pymor_vis:run

requirements:

  host:
    - python >=3.7
    - pip
    - numpy
    - packaging
    - pytest-runner
    - wheel

  run:
    - python >=3.7
    - typer
    - pythreejs
    - ipywidgets
    - ipython >=3.0
    - ipyparallel
    - matplotlib-base
    - pyopengl
    - diskcache
    - pyqt ==5.12.3
    - pillow
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.3
    - docopt
    - qtpy !=2.0.0
    - packaging
    - jupyter
    - pyvista

test:
  requires:
    - pytest >=4.6
    - hypothesis
    - packaging

  imports:
    - pymor
    - pymordemos

about:
  home: https://pymor.org
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: >
    pyMOR is a software library for building model order reduction applications
    with the Python programming language. All algorithms in pyMOR are formulated
    in terms of abstract interfaces, allowing generic implementations to work
    with different backends, from NumPy/SciPy to external partial differential
    equation solver packages.

extra:
  recipe-maintainers:
    - HenKlei
    - lbalicki
    - pmli
    - sdrave
